### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by reeshmabijosh** [walterra/covid-19-tirol-ds#9]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/MOY7I2
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by walterra** [comment]
Took me a while to catch up. I'd be happy to do that, however the link you posted to the datasets doesn't work anymore.
